[project]
name = "political-polarisation"
version = "0.1.0"
description = "Political Polarisation Experiment for the UK Government 2019 / 2024"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.5.0",
    "numba==0.61rc1",
    "datafusion>=43.1.0",
    "pyarrow>=18.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
vectorlink-gpu = { git = "ssh://git@github.com/vectorlink-ai/vectorlink-gpu" }
vectorlink-py = { git = "ssh://git@github.com/vectorlink-ai/vectorlink.py" }
